# external-secret-dev.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: magento-cloud-variables
  namespace: magento
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: magento-cloud-variables
    template:
      metadata:
        annotations:
          # Prevent ArgoCD from deleting this secret (created by External Secrets Operator)
          argocd.argoproj.io/sync-options: Prune=false
  data:
    - secretKey: "MAGENTO_CLOUD_VARIABLES"
      remoteRef:
        key: MAGENTO_CLOUD_VARIABLES
        property: "MAGENTO_CLOUD_VARIABLES"
    - secretKey: MAGENTO_CLOUD_ROUTES
      remoteRef:
        key: "MAGENTO_CLOUD_ROUTES"
        property: "MAGENTO_CLOUD_ROUTES"
    - secretKey: MAGENTO_CLOUD_RELATIONSHIPS
      remoteRef:
        key: "MAGENTO_CLOUD_RELATIONSHIPS"
        property: "MAGENTO_CLOUD_RELATIONSHIPS"
    - secretKey: mariadb-password
      remoteRef:
        key: "mariadb-password"
        property: "mariadb-password"
    - secretKey: mariadb-replication-password
      remoteRef:
        key: "mariadb-replication-password"
        property: "mariadb-replication-password"
    - secretKey: mariadb-root-password
      remoteRef:
        key: "mariadb-root-password"
        property: "mariadb-root-password"
    - secretKey: rabbitmq-password
      remoteRef:
        key: "rabbitmq-password"
        property: "rabbitmq-password"
    - secretKey: rabbitmq_user
      remoteRef:
        key: "rabbitmq_user"
        property: "rabbitmq-user"
    - secretKey: rabbitmq-erlang-cookie
      remoteRef:
        key: rabbitmq-erlang-cookie
        property: "rabbitmq-erlang-cookie"
