# secret-store.yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: {{ .Values.vault.serviceVault }}
      path: {{ .Values.vault.path }}
      version: "v2"
      namespace: "vault-system"
      auth:
        tokenSecretRef:
          name: {{ .Values.vault.existingSecret | default "vault-root-token" }}
          namespace: {{ .Values.vault.existingSecretNamespace | default "vault-system" | quote }}
          key: {{ .Values.vault.existingSecretKey | default "token" | quote }}