{{- if .Values.vault.token }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: vault-system
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-root-token
  namespace: vault-system
type: Opaque
stringData:
  token: {{ .Values.vault.token | quote }}
{{- end }}