{{- if index .Values "cert-manager" "enabled" }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ index .Values "cert-manager" "namespace" | default "cert-manager" }}
  labels:
    {{- include "magento.labels" . | nindent 4 }}
{{- end }}